name: Environment

on: [none]

jobs:
  build-environment:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis
        ports:
        - 6379/tcp

    steps:
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        version: 12.x

    - name: npm install & build
      run: |
        npm install
        npm run build --if-present
